language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_install:
- composer require phpunit/phpunit:5.* satooshi/php-coveralls:dev-master
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v